# gpu service
services:
  video_scene_split_test:
    image: catchoco/video-scene-split:latest
    container_name: video_scene_split_test
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - video_scene_split_test_net
    entrypoint: tail
    command: ["-f", "/dev/null"]