# gpu service
services:
  video_scene_split:
    image: catchoco/video-scene-split:latest
    container_name: video_scene_split
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - video_scene_split_net